package ua.com.shop.validator;

public interface UserValidationMassages {

	String EMPTY_NAME_FIELD ="EMPTY_NAME_FIELD";
	String EMPTY_SURNAME_FIELD ="EMPTY_SURNAME_FIELD";
	String EMPTY_EMAIL_FIELD ="EMPTY_EMAIL_FIELD";
	String EMPTY_PASSWORD_FIELD ="EMPTY_PASSWORD_FIELD";
	String EMAIL_ALREADY_EXIST ="EMAIL_ALREADY_EXIST";
	String PASSWORD_WRONG ="PASSWORD_WRONG";
	String THIS_EMAIL_IS_NOT_FOUND ="THIS_EMAIL_IS_NOT_FOUND";
	
}
